# Generated by Django 5.0.6 on 2024-06-08 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emisores',
            name='fecha',
            field=models.DateField(),
        ),
    ]
